sudo: required
language: generic
services:
  - docker

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
  #- docker login --username=$HEROKU_USERNAME --password=$HEROKU_PASSWORD registry.heroku.com
script:
  - docker build -t doviethoang093/docker-travis -f Dockerfile .
  - docker tag doviethoang093/docker-travis registry.heroku.com/ci-reactjs-travis/web
deploy:
  provider: script
  script:
    # push to dockerhub & heroku
    docker push doviethoang093/docker-travis;
    docker push registry.heroku.com/ci-reactjs-travis/web;
    heroku config:set REACT_APP_BASE_URL=https://picsum.photos/seed/picsum/200/300;
    heroku container:release web --app ci-reactjs-travis;
  on:
    branch: main
